// flow-typed signature: fd58228d7ff10fdbfb003521830405dc
// flow-typed version: <<STUB>>/react-native-maps_v^0.13.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-maps/components/AnimatedRegion' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/decorateMapComponent' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapCallout' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapCircle' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapMarker' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapPolygon' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapPolyline' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapUrlTile' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapView' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/ProviderConstants' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-maps/components/AnimatedRegion.js' {
  declare module.exports: $Exports<'react-native-maps/components/AnimatedRegion'>;
}
declare module 'react-native-maps/components/decorateMapComponent.js' {
  declare module.exports: $Exports<'react-native-maps/components/decorateMapComponent'>;
}
declare module 'react-native-maps/components/MapCallout.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapCallout'>;
}
declare module 'react-native-maps/components/MapCircle.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapCircle'>;
}
declare module 'react-native-maps/components/MapMarker.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapMarker'>;
}
declare module 'react-native-maps/components/MapPolygon.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapPolygon'>;
}
declare module 'react-native-maps/components/MapPolyline.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapPolyline'>;
}
declare module 'react-native-maps/components/MapUrlTile.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapUrlTile'>;
}
declare module 'react-native-maps/components/MapView.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapView'>;
}
declare module 'react-native-maps/components/ProviderConstants.js' {
  declare module.exports: $Exports<'react-native-maps/components/ProviderConstants'>;
}
declare module 'react-native-maps/index' {
  declare module.exports: $Exports<'react-native-maps'>;
}
declare module 'react-native-maps/index.js' {
  declare module.exports: $Exports<'react-native-maps'>;
}
