// flow-typed signature: ce8035c3f3fbf025ed5ed97a56fa171c
// flow-typed version: <<STUB>>/react-native-simple-modal_v^4.0.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-simple-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-simple-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-simple-modal/index' {
  declare module.exports: $Exports<'react-native-simple-modal'>;
}
declare module 'react-native-simple-modal/index.js' {
  declare module.exports: $Exports<'react-native-simple-modal'>;
}
