// flow-typed signature: 352d1393b65ebc56df252385403d43bd
// flow-typed version: <<STUB>>/react-native-nav_v^1.1.4/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-nav'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-nav' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-nav/components/NavButton' {
  declare module.exports: any;
}

declare module 'react-native-nav/components/NavButtonText' {
  declare module.exports: any;
}

declare module 'react-native-nav/components/NavGroup' {
  declare module.exports: any;
}

declare module 'react-native-nav/components/NavTitle' {
  declare module.exports: any;
}

declare module 'react-native-nav/components/StatusBarEnhanced' {
  declare module.exports: any;
}

declare module 'react-native-nav/gulpfile' {
  declare module.exports: any;
}

declare module 'react-native-nav/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-nav/components/NavButton.js' {
  declare module.exports: $Exports<'react-native-nav/components/NavButton'>;
}
declare module 'react-native-nav/components/NavButtonText.js' {
  declare module.exports: $Exports<'react-native-nav/components/NavButtonText'>;
}
declare module 'react-native-nav/components/NavGroup.js' {
  declare module.exports: $Exports<'react-native-nav/components/NavGroup'>;
}
declare module 'react-native-nav/components/NavTitle.js' {
  declare module.exports: $Exports<'react-native-nav/components/NavTitle'>;
}
declare module 'react-native-nav/components/StatusBarEnhanced.js' {
  declare module.exports: $Exports<'react-native-nav/components/StatusBarEnhanced'>;
}
declare module 'react-native-nav/gulpfile.js' {
  declare module.exports: $Exports<'react-native-nav/gulpfile'>;
}
declare module 'react-native-nav/index' {
  declare module.exports: $Exports<'react-native-nav'>;
}
declare module 'react-native-nav/index.js' {
  declare module.exports: $Exports<'react-native-nav'>;
}
declare module 'react-native-nav/styles.js' {
  declare module.exports: $Exports<'react-native-nav/styles'>;
}
