// flow-typed signature: 825d9ecd12a2c5f9228364ec5dd34337
// flow-typed version: <<STUB>>/react-native-debugger-open_v^0.3.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-debugger-open'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-debugger-open' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-debugger-open/bin/rndebugger-open' {
  declare module.exports: any;
}

declare module 'react-native-debugger-open/lib/injectDevToolsMiddleware' {
  declare module.exports: any;
}

declare module 'react-native-debugger-open/lib/injectDevToolsMiddleware.tmpl' {
  declare module.exports: any;
}

declare module 'react-native-debugger-open/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-debugger-open/bin/rndebugger-open.js' {
  declare module.exports: $Exports<'react-native-debugger-open/bin/rndebugger-open'>;
}
declare module 'react-native-debugger-open/lib/injectDevToolsMiddleware.js' {
  declare module.exports: $Exports<'react-native-debugger-open/lib/injectDevToolsMiddleware'>;
}
declare module 'react-native-debugger-open/lib/injectDevToolsMiddleware.tmpl.js' {
  declare module.exports: $Exports<'react-native-debugger-open/lib/injectDevToolsMiddleware.tmpl'>;
}
declare module 'react-native-debugger-open/lib/main.js' {
  declare module.exports: $Exports<'react-native-debugger-open/lib/main'>;
}
