// flow-typed signature: c568b36cf253242b6ce7470b6dce0475
// flow-typed version: <<STUB>>/react-native-root-modal_v^1.0.7/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-root-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-root-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-root-modal/Example/Animation' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/CustomStyle' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/Launch' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/main' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/react-native-navbar/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/react-native-navbar/NavbarButton' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/react-native-navbar/NavigatorBar' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/react-native-navbar/styles' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/Example/SimpleModal' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/lib/Modal' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/lib/ModalContainer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-root-modal/Example/Animation.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/Animation'>;
}
declare module 'react-native-root-modal/Example/CustomStyle.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/CustomStyle'>;
}
declare module 'react-native-root-modal/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/index.android'>;
}
declare module 'react-native-root-modal/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/index.ios'>;
}
declare module 'react-native-root-modal/Example/Launch.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/Launch'>;
}
declare module 'react-native-root-modal/Example/main.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/main'>;
}
declare module 'react-native-root-modal/Example/react-native-navbar/NavBar.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/react-native-navbar/NavBar'>;
}
declare module 'react-native-root-modal/Example/react-native-navbar/NavbarButton.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/react-native-navbar/NavbarButton'>;
}
declare module 'react-native-root-modal/Example/react-native-navbar/NavigatorBar.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/react-native-navbar/NavigatorBar'>;
}
declare module 'react-native-root-modal/Example/react-native-navbar/styles.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/react-native-navbar/styles'>;
}
declare module 'react-native-root-modal/Example/SimpleModal.js' {
  declare module.exports: $Exports<'react-native-root-modal/Example/SimpleModal'>;
}
declare module 'react-native-root-modal/lib/Modal.js' {
  declare module.exports: $Exports<'react-native-root-modal/lib/Modal'>;
}
declare module 'react-native-root-modal/lib/ModalContainer.js' {
  declare module.exports: $Exports<'react-native-root-modal/lib/ModalContainer'>;
}
