# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

update_fastlane
fastlane_version "2.54.4"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to the Google Play"
  lane :beta do
    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )
    gradle(task: "clean")
    gradle(task: "assembleRelease")
    supply(
      track: "alpha",
      track_promote_to: "beta",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )
    gradle(task: "clean")
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
